
# The name of your website.
name: Stijn van Cuijk

description:
  # Description of your site. This will show up in google.
  meta: Personal website and portfolio of Stijn van Cuijk, a designer currently studying Industrial Product Design at the HAN University of Applied Sciences.

portfolio:
  download-url: \#
  last-updated: 2018/8/26
  size: 84

cv:
  download-url: \#
  last-updated: 2018/8/5
  size: 12

# The URL of the homepage of your site (without trailing slash). Leave this
# empty when you run Jekyll locally.
url: http://localhost:4000
baseurl: ""

collections:
  fp-collection:
    output: true
    permalink: /:permalink

##################
# BUILD SETTINGS #
##################

exclude: [vendor]
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  - scope:
      path: ""
      type: fp-collection
    values:
      layout: page
      excerpt_separator: "<!--more-->"
